config_location="/usr/local/opt/openalpr/share/openalpr/config/openalpr.defaults.conf"
runtime_data="/usr/local/opt/openalpr/share/openalpr/runtime_data/"
face_cascade="visual_descriptors/haarcascade_frontalface_default.xml"
profile_cascade="visual_descriptors/haarcascade_profileface.xml"
input_video="sample_videos/plate_movie.mp4"
output_video="sample_output/output.mov"
red = (0, 0, 255)
yellow = (0, 255, 255)
black = (0, 0, 0)
white = (255, 255, 255)
blue = (255, 0, 0)
